language: ruby
cache: bundler
rvm:
	- 2.1.1
before_script:
	- psql -c 'create database prayer_movements_test;' -U postgres
	- cp config/database.yml.travis config/database.yml
script:
	- RAILS_ENV=test bundle exec rake --trace db:migrate test
deploy:
  provider: heroku
  api_key:
    secure: Ev83Ou/pYMk9d5h989a3Mw5sRXHzuBJdnWtZXn+ZhkQtgO/+if4Cl5gGKxjRkxpukEK4ySt8g/7XQcS2NKS9mCQtZS6a+1TKlm5E7l/PIDTtQ5hW0Bd4t9E8MFpVI16i5hpEqeSXVdyaz2Jitke/s2A2454rhEQnHtq9P6TLTxU=
  app:
    master: prymv-staging
    production: prymv
  on:
    repo: StudentLifeDigtal/prayer_movements_server
  run:
    - "rake db:migrate"
    - restart
    - "rake cleanup"
addons:
   code_climate:
     repo_token: 8f0ab3e4e6829f500e8c4bf10f1b6f1de24a8e454b7553cd1cd42648232a2f63