language: ruby
cache: bundler
rvm:
 - 2.1.0
env:
  global:
  - AMAZON_S3_BUCKET=slnz_bundle_cache
  - AMAZON_ACCESS_KEY_ID=AKIAJQKGKDVVEYOJWQEQ
  - secure: "FbC37s42jwrbTA8buE5NyydyhUHPjpWlhdlFSN76GfCcuwAS+Ic2/U4dZ3dpQCPon7v1Xq1PsJKbjGeDcb9xxMyGfYx3xvzFT5VXdZ++cM0STiI/BcFtONziLekmbdrobg4OEKfDIppIbktZvCF9mtcP4Klyv7/TNVZjSPwWNl0="
install:
 - script/cached-bundle install --deployment
before_script:
 - psql -c 'create database prayer_movements_test;' -U postgres
 - cp config/database.yml.travis config/database.yml
 - bundle exec rake db:migrate RAILS_ENV=test
script:
 - RAILS_ENV=test bundle exec rake
deploy:
 provider: heroku
 strategy: git
 api_key:
  secure: Ev83Ou/pYMk9d5h989a3Mw5sRXHzuBJdnWtZXn+ZhkQtgO/+if4Cl5gGKxjRkxpukEK4ySt8g/7XQcS2NKS9mCQtZS6a+1TKlm5E7l/PIDTtQ5hW0Bd4t9E8MFpVI16i5hpEqeSXVdyaz2Jitke/s2A2454rhEQnHtq9P6TLTxU=
 app:
  master: prymv-staging
  production: prymv
 run: "rake db:migrate"
 on:
  repo: slnz/prymv
addons:
 code_climate:
  repo_token:
    secure: "u30YVV/IN38DcGst62vFjZi5jn/5yoTU/fEXo2h1CeY//g1e67B/l8Ilf3EJmLU+NXAOc4bwFs04u4ip3pCvZ+HiWl4uPSG7RwJK58chBvX/qHXZ23jmTXfhHfPTxOin9cdcO3nlWF4z6+An7NK1upbcF/8Y3/qQqkn/QbQkDJ8="
notifications:
  flowdock:
    secure: "QrypDCmNTfFV+t4ytfq5aOwcxvNN1ZCdGuj206SOMAjNLOCbY2rmYBKt0U3KBxgI3UrQTguSjYezxTtcweKL29qyI8E6v+1t/cBAAMDReU1o2BKE2bNqOsH4idKtReg55kOzSUPstDWUciNgJ1SJnp1uNTp63jxXWiJmGe/eALE="
